#!/bin/sh

build_code=`date +%s`
build_date=`date`
build_box=`uname -a`
#build_cmd=`history !-1`
BCF='buildcodes.h'

printf "\n// Autogenerated buildcode file - this will change on every make\n" > $BCF
printf "#define BUILD_CODE \"$build_code\"\n" >> $BCF
printf "#define BUILD_DATE \"$build_date\"\n" >> $BCF
printf "#define BUILD_BOX \"$build_box\"\n" >> $BCF
#printf "#define BUILD_CMD \"$build_cmd\"\n" >> $BCF

printf "\n" >> $BCF

exit 0
